dfinke/ImportExcel

ImportExcel.psm1

Hi Doug!
As you mentioned, this might help if ChartTypes are changed down the road; substituted the ValidateSet out for a type which still provides intellisense:
Thanks again for the excellent module, this has been very helpful - Cheers!

Replace ValidateSet with EPPlus type

---

ImportExcel.psm1
TestImportExcel.ps1

I've had a use case where I needed a file to be read while opened in Excel. 
It's a simple change, I doubt it will break anything.
The only thing this does is open the file handle with FileShare flag set to ReadWrite instead of Read, so it doesn't throw "The process cannot access the file 'X' because it is being used by another process" when trying to Import-Excel it.

Allow reading a file already open in Excel

---

Export-Excel.ps1

Adjust code for -PivotData to allow use of an ordered dictionary
This allows users to maintain the order of their PivotData fields when exporting to Excel if they pass a hashtable of the format:  `[ordered]@{}`
A standard PowerShell hashtable does not retain the order of the keys when you enumerate it.

Allow ordered dictionary for PivotData

---

Export-Excel.ps1

Changed the TitleBold parameter to a Switch for a better PowerShell experience. I also added some logic so that if the user specifies a title background color and do not set a TitlePattern to something other than None, they will get a warning message, but the rest of the Excel workbook will be created.

Updated Title related parameters

---

ImportExcel.psm1

Currently, when you give Import-Excel an invalid path you get:
Cannot convert argument "1", with value: "Open", for "FileStream" to type "System.IO.FileAccess": "Cannot convert value "Open" to type "System.IO.FileAccess". Error: "Unable to match the identifier name Open to a valid enumerator name. Specify one of the following enumerator names and try again:
Read, Write, ReadWrite""
Took me a while to troubleshoot that down to me being stupid and not giving it a valid path.  This will make the Cmdlet error out before it ever runs.

Added ValidateScript block to Path parameter for Import-Excel

---

Export-Excel.ps1

This fixes #82 
Now a list of ranges passed as YRange results in multiple series in a single chart.

Fix for #82: multiple series aren't supported in a single chart.

---

Export-Excel.ps1

By default, calculated values for PivotTable data appears on rows.  This switch changes that behavior so the calculated values appear on columns instead.

Adds switch for PivotDataToColumn

---

Export-Excel.ps1

Fixed issue #44 with conditional formatting code that was breaking in Powershell 3

Powershell 3.0 compatibility fix

---

Export-Excel.ps1
ImportExcel.psm1

Fixed handling of the TableName with parameter validation, we now throw
an error in case the TableName:
- starts with something else then a letter
- is NULL or empty
- Contains spaces
Just like in the orriginal EPPlus.dll library.
Added Try/Catch clause for the End clause. So errors like 'TableName is
not unique' are terminating errors and the function isn't executed any
further.
Also cleaned up for readability some cosmetic stuff:
- 'if(' to 'if ('
- double quotes to single quotes where needed

Fix for Export-Excel #165

---

ImportExcel.Tests.ps1
ImportExcel.psd1
ImportExcel.psm1
README.md

**Bumped version to 4.0.1**
- Renamed 'TopRow' to 'StartRow' and added alias
(More concise with future parameter names like 'StartColumn')
- Removed 'ChangeList' in 'Notes' as this is tracked in Git
- Added parameter 'Password' to import password protected files
- Added Pester tests for parameter aliasses and:
- parameter 'Password'
- parameter 'Path' validation for extensions '.xls' and '.xlsx'
- 'HeaderName' witb blanks
- Changed comments in Pester tests from '<# Comment #>' to '# Comment'
(Easier to comment out a whole block of tests when performing a test on a specific piece of code)

Import excel added parameter 'Password'

---

Export-Excel.ps1
README.md

This PR is an attempt at fixing both issues #182 and #89.
Attached is a test script to reproduce the issues in old and new code.
[ImportExcelPRSample.zip](https://github.com/dfinke/ImportExcel/files/1349151/ImportExcelPRSample.zip)

Title fix (Issues #182 and #89)

---

Export-Excel.ps1
ImportExcel.psm1

Fix Bug, AutoFilter with TableName create corrupted Excel file.
https://github.com/dfinke/ImportExcel/issues/65
You now cannot set AutoFilter and TableName at the same time.
"-Now" will not auto add AutoFilter if TableName set.

Fix Bug. AutoFilter with TableName corrupted file

---

Export-Excel.ps1
Export-charts.ps1
ImportExcel.psm1
Open-ExcelPackage.ps1
formatting.ps1

I changed Export-Excel.ps1 as follows. 
#1 @ Line 197 Made new parameter sets . Default, and table already
existed and use path. Added DefaultPackage and TablePackage
A New parameter  "Package" allows an ExcelPackage object returned by
-passThru to be passed in
~Line 400 code to use package or path depending on path passed.
(also added Open-ExcelPackage  to get the object without exporting and
Close-ExcelPackage to close it nicely - these are in their own file)
#2.  @ Line 256 added new parameter excludeProperty to remove unwanted
properties without needing to go through select-object
~Line 459 added logic to exclude the properties specified in the new
parameter
#3 .  @ Line 262 Added new parameter Append
~Line 420 code to read the existing headers and move the insertion point
below the …

My changes to support append, and formatting

---

Send-SqlDataToExcel.ps1

A second SQL connection may begin in a closed state, previously code assumed all connections begin as "open". 
Fixed bugs with ChangeDatabase parameter which would prevent it working

SQL Server related bug fixes in Send-SQLDataToExcel.ps1

---

ConvertFromExcelToSQLInsert.ps1

This PR attempt to provide a workaround for #288, where empty strings causes an INT column to be added with value of 0 instead of NULL. 
I've introduced a new parameter `-ConvertEmptyStringsToNull`. If specified, it will cause the resulting insert statement to have NULL instead of an empty string (`''`).

Replace empty string with NULL when generating SQL inserts. Fixes #288

---

AddConditionalFormatting.ps1
Export-Excel.ps1
ImportExcel.psm1
README.md
Set-Column.ps1
Set-Row.ps1
SetFormat.ps1
ToDo.md
__tests__/Compare-WorkSheet.tests.ps1
__tests__/Copy-ExcelWorksheet.Tests.ps1
__tests__/Export-Excel.Tests.ps1
__tests__/Join-Worksheet.tests.ps1
__tests__/Set-Row_Set-Column-SetFormat.tests.ps1

- Fixed a bug (typo) in Set-Format which caused -Hidden not to work 
- Import-Excel now has an argument completer for Worksheet name - this can be slow on large files
- The NumberFormat parameter (in Export-Excel, Set-Row, Set-Column, Set-Format and Add-ConditionalFormat) and X&YAxisNumberFormat paramaters (in New-ExcelChartDefinition and Add-ExcelChart) now have an argument completer and the names Currency, Number, Percentage, Scientific, Fraction, Short Date ,Short time,Long time, Date-Time and Text will be converted to the correct Excel formatting strings. 
- Added new function Select-Worksheet to make a named sheet active: Added -Activate switch to Add-Worksheet, to make current sheet active, Export-Excel and Add-PivotTable support -Activate and pass it to Add-Worksheet, and …

Argument completers for Number format and Worksheetname, bug fix for hidden in set format & more

---

New-ExcelChart.ps1
README.md

Two small tweaks to Add-Chart
(a) A series header was always set as literal string. Now if it begins with = what follows the = sign is set as the header address (so labels can come from cells)
(b) in #420 and #486 there is discussion of adding some code so if there were many X ranges each Y range got its own X range. This never got added to the code I checked in, but it's in now.

Chart supports multiple X ranges and headers from cells

---

Export-Excel.ps1
ImportExcel.psd1
README.md
Send-SqlDataToExcel.ps1
__tests__/Copy-ExcelWorksheet.Tests.ps1
__tests__/First10Races.tests.ps1
__tests__/InputItemParameter.tests.ps1
__tests__/Set-Row_Set-Column-SetFormat.tests.ps1

I had to roll back the changes I made to the readme so github would accept the changes could be merged. So here .... 
- **Performance improvement to Export-Excel** see #506 and #555. This has meant taking code in `Add-CellValue` back into process block of Export-Excel, as the overhead of calling the function was a lot greater than time executing the code inside it. [Blog post to follow](https://jamesone111.wordpress.com). Some tests are showing a ~10x speed increase. #572 was about a broken #region tag in this part of the code and that has been cleaned up in the process. 
- Export-Excel now has an `-InputObject` parameter (this was previously `-TargetData` , which is now an alias for InputObject).
If the `inputobject` is an array, each item will be inserted, so you can run `export-excel …

Perf improvements for Export-Excel

---

.gitignore
__tests__/Compare-WorkSheet.tests.ps1

The test call the command `Compare-WorkSheet` with the switch `-GridView` then sends "Alt + F4" to the active window.
The problem is that if the `Out-GridView` is not in focus the test will close the focused window whether it's the `Out-GridView` or not. (Usually it closes my VSCode).
The fix open the GridView in a new PowerShell instance that closes itself when it finished.

Fix Test accidentally closing focused window

---

Export-Excel.ps1
__tests__/Export-Excel.Tests.ps1

Export-Excel help gives the following info:
```
.PARAMETER TableStyle
Selects the style for the named table - defaults to 'Medium6'.
```
We define the default in Export-Excel `[OfficeOpenXml.Table.TableStyles]$TableStyle = 'Medium6',` then ignoring it `if ($PSBoundParameters.ContainsKey('TableStyle'))`
Then define it again in `Add-ExcelTable` and then ignore it again.
So I remove the definition from Export-Excel as it is redundant and stopped ignoring it in Add-ExcelTable

TableStyle is set to Medium6 but ignored

---

AddDataValidation.ps1
ConvertExcelToImageFile.ps1
ConvertToExcelXlsx.ps1
Export-Excel.ps1
Install.ps1
Join-Worksheet.ps1
Send-SqlDataToExcel.ps1
SetFormat.ps1
__tests__/InputItemParameter.tests.ps1

I was seeing that the new version was twice as slow compared to my old one, after some investigation I found that the ` | Out-Null` on `LoadFromDataTable` was changing it's execution time on the line from 0 to as long as the xlsx saving time doubling the total execution time.
I also replaced all the `Out-Null` in the module just in case it cusses slowdown in other places.
@jhoneill never use `Out-Null` it's pure evil https://stackoverflow.com/a/5263780

Double DataTable performance

---

AddConditionalFormatting.ps1
ColorCompletion.ps1
Export-Excel.ps1
ImportExcel.psd1
ImportExcel.psm1
New-ConditionalText.ps1
SetFormat.ps1
__tests__/ConvertFromExcelToSQLInsert.tests.ps1

As it says in the commit comments, a couple of small style things, so export-excel can apply text styles as needed. (#606) 
Functionality looks like 
```
$style = New-ExcelStyle -BackgroundColor LightBlue -FontSize 14 -Bold -Range "A1:H1" -HorizontalAlignment Center -Merge
$data | Export-Excel $f -AutoSize -AutoFilter -Title $reportTitle  -Style $style -sho
```
And a fix for importing files even if they are open ( #607 ). Also had a path issue in one of the tests so made sure it writes to temp.

Style and read only

---

Export-Excel.ps1
ImportExcel.psm1
Merge-Worksheet.ps1
Send-SQLDataToExcel.ps1
SetFormat.ps1
__tests__/AddTrendlinesToAChart.tests.ps1
__tests__/CI.ps1
__tests__/Compare-WorkSheet.tests.ps1
__tests__/ConvertFromExcelToSQLInsert.tests.ps1
__tests__/Export-Excel.Tests.ps1
__tests__/First10Races.tests.ps1
__tests__/FunctionAlias.tests.ps1
__tests__/ImportExcelTests/Simple.tests.ps1
__tests__/InputItemParameter.tests.ps1
__tests__/Remove-WorkSheet.tests.ps1
__tests__/Set-Row_Set-Column-SetFormat.tests.ps1

Linux. Now set an environment variable if the support needed for Autosize is present, and use that Environment variable to decide to skip autosize operations. 
Fixed a couple of tests which needed autosize to work so they skip of the enivronment variable is set. 
Fixed another break where on azure the module never loaded. 
Added  -Force to Send-SQLDataToExcel so it sends something even if no rows are returned. (see #703) 
Added -asText to import-Excel see #164 and multiple others 
Simple tests added for both of these. . 
Add a comment to ci.ps1 re better .NET version detection and left some commented out code.

SQL -Force , import -asText , test fixes, better Linux behavior

---

Public/Import-Excel.ps1
__tests__/ImportExcelHeaderName.tests.ps1

@jhoneill this "works". Might be opening a can of worms. Added a couple tests. One for the issue and the other using the `-NoHeader` switch. 
If there is no data, returns null, as does `ConvertFrom-Csv`
More tests? Rework? Thoughts?

Spike to fix #792

---

Public/Add-ConditionalFormatting.ps1
Public/Add-ExcelName.ps1
Public/Add-PivotTable.ps1
Public/Compare-Worksheet.ps1
Public/Convert-ExcelRangeToImage.ps1
Public/ConvertFrom-ExcelData.ps1
Public/ConvertFrom-ExcelToSQLInsert.ps1
Public/Copy-ExcelWorksheet.ps1
Public/Export-Excel.ps1
Public/Import-Excel.ps1
Public/Join-Worksheet.ps1
Public/Merge-MultipleSheets.ps1
Public/Merge-Worksheet.ps1
Public/Set-ExcelColumn.ps1
Public/Set-ExcelRow.ps1

* standardise 'worksheet' as a single word, instead of 'workSheet' or 'WorkSheet'
* main parameter names starting with capital letter $WorksheetName
* supporting variable names starting with lower letter $worksheetName

Standardising casing of parameter names

---

Examples/ConditionalFormatting/Databar.ps1

As noted in the comments -Address is an alias for -Range
In current form it's giving an error:
```
Set-ExcelRange : Missing an argument for parameter 'Range'. Specify a parameter of type 'System.Object' and try again.
At line:1 char:16
+ Set-ExcelRange -Range -Address $sheet.Cells["E1:H1048576"]  -Horizont ...
+                ~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Set-ExcelRange], ParameterBindingException
+ FullyQualifiedErrorId : MissingArgument,Set-ExcelRange
```

Example: Removed a duplicate parameter Range/Address

---

Public/ConvertFrom-ExcelSheet.ps1

UNC paths broken with just Path property of Resolve-Path, looks like it was fixed elsewhere but overlooked here.

Fix UNC paths for ConvertFrom-ExcelSheet

---

Public/ConvertFrom-ExcelToSQLInsert.ps1

If data in the Excel file contains single quotes, then the insert will bomb as it will be malformed. Quotes would need escaped. Not all languages will support the same escape method, so I recommend it being set by an optional parameter.
Example of what will fail:
Name
Fry's
INSERT INTO [Name] Values ( 'Fry's' )
Corrected for quotes (such as needing to escape a single quote with an additional single quote)
INSERT INTO [Name] Values ('Fry''s')
Example code:
$ConvertToSqlParams = @{TableName = ‘dbo.Names’
Path = ‘C:\temp\data.xlsx’
ConvertEmptyStringsToNull = $true
UseMSSQLSyntax = $true
SingleQuoteStyle = "''"
}
$SQLInsert = ConvertFrom-ExcelToSqlInsert @ConvertToSqlParams

Allow for escaping of single quote in data.

---

Public/Add-ConditionalFormatting.ps1

This is to correct an error in Conditional formatting that was preventing "Bottom" from working.

Update Bottom Spelling Error

---

Public/Add-Worksheet.ps1

Due to some foolishness on my part, I saw this warning several times, so the 'worsheet' typo started to get to me.

Update Add-Worksheet.ps1 - 'worsheet' to 'worksheet' in warnings

---

Public/Set-ExcelRange.ps1

Noticed while using the Set-ExcelRange/Set-Format function.

Fixed typo of 'pararameter' to 'parameter'

---

ImportExcel.psd1
Public/ConvertFrom-ExcelData.ps1
changelog.md

Fix issue where none of 'HeaderRow', 'TopRow' and 'StartRow' work in ConvertFrom-ExcelToSQLInsert, preventing you from skipping rows.
Issue is that aliases are missing from the parameter list of ConvertFrom-ExcelData. 
ConvertFrom-ExcelToSQLInsert accepts 'HeaderRow', 'TopRow' and 'StartRow', but passes 'StartRow', while  ConvertFrom-ExcelData only accepts 'HeaderRow'
FIX: Alter ConvertFrom-ExcelData to have the same aliases for the parameter as both its caller, ConvertFrom-ExcelToSQLInsert and its callee, Import-Excel. All three now have:
[Alias('HeaderRow', 'TopRow')]
[Int]$StartRow = 1,

Add missing parameter aliases to align with caller/callee

---

Public/ConvertTo-ExcelXlsx.ps1

This could help prevent file locking issues. Also put everything in a try-finally to be extra sure that it will quit.
Just some extra guardrails.
see also: https://learn.microsoft.com/en-US/dotnet/api/microsoft.office.interop.excel.workbooks.open
I tested this locally and it works

[ConvertTo-ExcelXlsx] open XLS as read-only
