dfinke/ImportExcel

ImportExcel.psm1

I *think* I am doing this correctly. Haven't really done a pull request before.

Export-Excel now resolves unresolved pspaths.

---

ImportExcel.psm1

Added function to export all sheets into csv files Export all sheets

Added Import-ExcelAllSheet

---

Export-Excel.ps1

Improved help by adding a richer explenation of the different parameters
and better examples. Also note that 'TitleBold' is no longer of type
Boolean but is now a switch as it can only true or false.

Added help for Export-Excel

---

Export-Excel.ps1

Improved code formatting and added 'Path' parameter validation. When a path doesn't exist we throw an error. When the file extension provided by the user isn't correct, we throw an error.

Test branch

---

Export-Excel.ps1

Ensure Datalabel is not null before referencing it.

---

README.md

Update the installation instructions to be more direct and precise, making it easier for someone to get started. Also add the -scope CurrentUser method as an option which doesn't require admin privileges.

Update README.md Installation Instructions

---

Export-Excel.ps1
Install.ps1

removing extra spaces after the backtick

---

Export-Excel.ps1

uninitialized variable $idx leaks into the pipeline when -TableName parameter is used.

---

Export-Excel.ps1
Get-ExcelSheetInfo.ps1
Get-ExcelWorkbookInfo.ps1
ImportExcel.psm1

Fix for #162 
- Added help text for 'Import-Excel'
- Added 'DataOnly' parameter to 'Import-Excel'
- Improved 'Get-ExcelSheetInfo'

Fix for #162 and other improvements

---

ImportExcel.Tests.ps1
ImportExcel.psm1
README.md

'-WorksheetName' is now optional. If not used the first worksheet will be selected.

Import excel first worksheet

---

ImportExcel.Tests.ps1
ImportExcel.psm1

- Fixed position of `-WorksheetName` parameter
- Added extra Pester tests for parameters

Import-Excel parameter

---

Export-Excel.Tests.ps1
Export-Excel.ps1

Fix for #222 and added some more Pester tests.

Fixed zero exported as String instead of numerical

---

Install.ps1

Install.ps1 did not contains all needed scrips references to files. Thus import module has failed with error complaining for missing files. This should resolve issue for now.

Updated Install.ps1 to install module for PowerShell V4

---

AddConditionalFormatting.ps1
ColorCompletion.ps1
Examples/Index - Music.ps1
Examples/SQL+FillColumns+Pivot/Example2.ps1
Export-Excel.ps1
ImportExcel.psd1
Join-Worksheet.ps1
New-ConditionalText.ps1
New-ExcelChart.ps1
Open-ExcelPackage.ps1
PivotTable.ps1
README.md
Send-SqlDataToExcel.ps1
Set-Column.ps1
Set-Row.ps1
SetFormat.ps1
__tests__/Export-Excel.Tests.ps1
__tests__/Join-Worksheet.tests.ps1
__tests__/Set-Row_Set-Column-SetFormat.tests.ps1
compare-worksheet.ps1

Small bug fix on -AutoNameRange and now allow 
`1..5 | set-column -worksheet $ws -AutonameRange
`
Test for an empty dataset in send-sqlDataToExcel didn't do the job . 
JoinWorksheet didn't have to color argument completer and couldn't take background color on its own. 
Better tests, examples and Help.

Minor improvements

---

Export-Excel.ps1
Send-SqlDataToExcel.ps1
__tests__/Export-Excel.Tests.ps1

Fix for bug handling null and zero; date format applied in send-sql

---

Export-Excel.ps1
ImportExcel.psm1

Added an example for running a query from a SQL Server database using the Invoke-Sqlcmd cmdlet, and then exporting the results to Excel.

Added Example for SQL Server

---

ImportExcel.psm1
Merge-worksheet.ps1
Set-Column.ps1
Set-Row.ps1
SetFormat.ps1
__tests__/Compare-WorkSheet.tests.ps1
__tests__/FunctionAlias.tests.ps1
__tests__/Set-Row_Set-Column-SetFormat.tests.ps1

Found Import-Excel had Write-verbose for each cell; removed this for perf. 
Some parameter combinations with Merge-MultipleWorksheets didn't work as they should, because of an issue in Merge-Worksheet, so fixed that. Also fixed a conditional format bug in Merge-Worksheet which meant some backgroundColor didn't show because the background pattern was none instead of solid. 
Code for setting font name was missing. Added to it set-excelRange and made sure it was passed from set excel-Row/column. Added teststs for these.

Fixed #457 & a couple more tweaks

---

Export-Excel.ps1
New-ConditionalText.ps1
README.md
Set-Column.ps1
Set-Row.ps1

#491 is the To do for issue #490

TO Do #491 Done

---

Export-Excel.ps1

Update Export-Excel.ps1 - Add-Worksheet help typo

---

ImportExcel.psm1
__tests__/ImportExcelTests/Simple.tests.ps1

As it says in the title. I've added an ExcelPackage parameter and switched the open and close file logic when there is a path to use the Open-ExcelPackage and Close-ExcelPackage function. Also some small tweaks to help text.

Allow import Excel to take packages not just paths

---

Examples/Charts/ChartAndTrendlines.ps1
New-ExcelChart.ps1
__tests__/AddTrendlinesToAChart.tests.ps1

Initial pass at adding ChartTrendLine

---

Get-ExcelColumnName.ps1

Column letters were returned out of order.  Issue #708
Not done this before - comments welcome

Fixes Column order issue

---

__tests__/Get-ExcelColumnName.Test.ps1

Adding test for Get-ColumnName

---

Public/Import-Excel.ps1

These outputs are unnecessary and can confuse someone observing other debug output.

Remove Write-Debug Performance Outputs

---

CI/PS-CI.ps1
appveyor.yml
azure-pipelines.yml

Add `-MaximumVersion 4.99.99` on `Install-Module Pester`. In `yml` files and `ps1`.

Prevent install of Pester v5

---

Public/Add-PivotTable.ps1
Public/Add-Worksheet.ps1
Public/Convert-ExcelRangeToImage.ps1
Public/ConvertFrom-ExcelData.md
Public/ConvertFrom-ExcelData.ps1
Public/ConvertFrom-ExcelToSQLInsert.ps1
Public/Copy-ExcelWorksheet.ps1
Public/Export-Excel.ps1
Public/Get-ExcelColumnName.md
Public/Get-ExcelColumnName.ps1
Public/Get-HtmlTable.md
Public/Get-HtmlTable.ps1
Public/Get-Range.md
Public/Get-Range.ps1
Public/Get-XYRange.md
Public/Get-XYRange.ps1
Public/Import-Html.md
Public/Import-Html.ps1
Public/Invoke-Sum.md
Public/Invoke-Sum.ps1
Public/Join-Worksheet.ps1
Public/Merge-MultipleSheets.ps1
Public/Merge-Worksheet.ps1
Public/New-PivotTableDefinition.ps1
Public/Send-SQLDataToExcel.ps1
Public/Set-CellStyle.md
Public/Set-WorksheetProtection.md

More of the parameters starting with lower letter + 'workSheets'.

Variable casing

---

CI/CI.ps1
ImportExcel.psm1
__tests__/ImportExcelTests/TestImportOnly.tests.ps1
azure-pipelines.yml

fixes #832

---

Examples/PesterTestReport/Pester test report.ps1
Examples/PesterTestReport/PesterConfiguration.json

This example is compatible with the latest Pester. I left the old example for use with Pester 4.

Added example for exporting data to Excel for Pester 5.1

---

README.md

The What's new for 7.1.2 starts at line 58

Removed duplicate entry for the version

---

azure-pipelines.yml

Test adding ACE drivers into the testing pipeline.

Add ACE into testing pipeline

---

ImportExcel.psd1
Private/Invoke-ExcelReZipFile.ps1
Public/Close-ExcelPackage.ps1
Public/Export-Excel.ps1
changelog.md

- Implements: https://github.com/dfinke/ImportExcel/issues/1111
- Refactored ReZip into separate function
- Deletes temp folder after rezipping
- Added -ReZip to `Close-ExcelPackage`

Refactor-rezip

---

Examples/ConditionalFormatting/Highlight-DiffCells.ps1
changelog.md

Example based on #1201 discussion

Compare cells

---

mdHelp/en/open-excelpackage.md

Open-ExcelPackage Example 2 Line:48
remove 'and'

Fix typo in help

---

mdHelp/en/export-excel.md

Resolve Spelling in Help file: export-excel.md

#1281 Grammar error update

---

Public/Export-Excel.ps1
__tests__/Export-Excel.Tests.ps1
changelog.md
mdHelp/en/export-excel.md

This should fix Issue #1316 
Added tests and documentation

Add -NoHyperLinkConversion

---

ImportExcel.psd1
Public/Get-ExcelFileSchema.ps1
__tests__/Get-ExcelFileSchema.tests.ps1
changelog.md

- Read an xlsx file
- Read all tabs
- Return a json schema of the metadata

Add Get-ExcelFileSchema

---

.github/workflows/ci.yml
Examples/Charts/ChartDataSeparatePage.ps1
changelog.md

Added example script to  illustrate creating a chart on one excel worksheet when the data is on another worksheet.

ChartDataSeparatePage.ps1

---

ImportExcel.psd1

Remove old pesterbdd URL in Import-excel.psd1 due to conflicts with AV sollutions.

Remove flagged URL
